var SimpleTabView = {};
SimpleTabView.active = function(e) { if(null != e) { var t = e.getAttribute("tabId"),
			n = jQuery(e).parent().find(".tabtitle");
		n.each(function() { null != this.getAttribute("tabId") && (e == this ? jQuery(this).addClass("current") : jQuery(this).removeClass("current")) }), null != t && (n = jQuery(e).closest(".tabcontainer").find(".tabpanel"), n.each(function() { null != this.getAttribute("tabId") && (this.style.display = this.getAttribute("tabId") == t ? "block" : "none") })) } };
var BookmarkSupport = {};
BookmarkSupport.bind = function(e) { e.find(".jrsj_plus").hover(function() { var e = jQuery(this); return e.removeClass("li_sec"), e.addClass("add"), e.html(""), !1 }, function() { var e = jQuery(this); if(e.removeClass("add"), e.addClass("li_sec"), null != e.attr("order")) { e.html(e.attr("order")); try { if(document.selection) document.selection.empty();
				else { var t = document.getSelection();
					t.removeAllRanges() } } catch(n) {} } return !1 }), e.find(".jrsj, .jrsj_plus").attr("title", "加入书架"), e.find(".jrsj_plus").parent().hover(function() { jQuery(this).find(".jrsj_plus").mouseover() }, function() { jQuery(this).find(".jrsj_plus").mouseout() }), e.find(".jrsj, .jrsj_plus").click(function() { var e = jQuery(this).attr("bookId"); if(null == e && "" == jQuery.trim(e)) return MessageDialog.open("系统错误, 请稍候重试 !"), !1; if(null == window.user || void 0 == window.user) { var t = jQuery(this); return UserManager.login(function() { t.click() }), !1 } jQuery.ajax({ type: "get", url: "http://www.zongheng.com/api/bookshelf.htm", data: { bookId: e }, dataType: "jsonp", async: !0, error: function() { MessageDialog.open("系统错误, 请稍候再试 !") }, success: function(e) { e && e.mes && MessageDialog.open(e.mes) } }) }) }, jQuery(function() { BookmarkSupport.bind(jQuery("body")), jQuery(".tabtitle").each(function() { var e = jQuery(this),
			t = null != e.attr("event") ? e.attr("event") : "mouseover";
		e.bind(t, function() { return SimpleTabView.active(this), !1 }) }), jQuery(".tab_block").hover(function() { jQuery(this).find(".jrsj").show() }, function() { jQuery(this).find(".jrsj").hide() }), jQuery(".ui-book-panel").hover(function() { jQuery(this).find(".detail-panel").show() }, function() { jQuery(this).find(".detail-panel").hide() }) });